services:
  postgres:
    container_name: postgres-sql-sa
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: stock_advisor
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - stock-network
    restart: unless-stopped
    
  keycloak:
    container_name: keycloak-sa
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: realm-sd-export.json
    volumes:
      - ./realm-sd-export.json:/opt/keycloak/data/import/realm.json
    networks:
      - stock-network
    command:
      - start-dev
      - --import-realm

  frontend:
    container_name: stock-advisor-frontend
    build:
      context: ./stock-portfolio-advisor-frontend
      dockerfile: Dockerfile
    image: stock-ad-fr
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - stock-network
    depends_on:
      - keycloak

  backend:
    container_name: stock-advisor-backend
    build:
      context: ./stock-portfolio-advisor-backend
      dockerfile: Dockerfile
    image: stock-ad-bk
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./stock-portfolio-advisor-backend/.env
    networks:
      - stock-network
    depends_on:
      - postgres
      - keycloak

networks:
  stock-network:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local
  frontend:
    driver: local
  backend:
    driver: local