services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=stock-advisor-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=stock-advisor-user'
    ports:
      - '5432:5432'
    restart: unless-stopped
