version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-ad-fr
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - frontend-data:/app/.next/cache
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  frontend-data:

networks:
  default:
    external:
      name: stock-network
